export const COUNTRY_NAMES: Record<string, string> = {
	AF: 'Afghanistan',
	AL: 'Albania',
	DZ: 'Algeria',
	AR: 'Argentina',
	AU: 'Australia',
	AT: 'Austria',
	BD: 'Bangladesh',
	BE: 'Belgium',
	BO: 'Bolivia',
	BR: 'Brazil',
	BG: 'Bulgaria',
	CA: 'Canada',
	CL: 'Chile',
	CN: 'China',
	CO: 'Colombia',
	HR: 'Croatia',
	CU: 'Cuba',
	CZ: 'Czech Republic',
	DK: 'Denmark',
	DO: 'Dominican Republic',
	EC: 'Ecuador',
	EG: 'Egypt',
	SV: 'El Salvador',
	EE: 'Estonia',
	FI: 'Finland',
	FR: 'France',
	DE: 'Germany',
	GH: 'Ghana',
	GR: 'Greece',
	GT: 'Guatemala',
	HN: 'Honduras',
	HK: 'Hong Kong',
	HU: 'Hungary',
	IS: 'Iceland',
	IN: 'India',
	ID: 'Indonesia',
	IR: 'Iran',
	IQ: 'Iraq',
	IE: 'Ireland',
	IL: 'Israel',
	IT: 'Italy',
	JM: 'Jamaica',
	JP: 'Japan',
	JO: 'Jordan',
	KZ: 'Kazakhstan',
	KE: 'Kenya',
	KR: 'South Korea',
	KW: 'Kuwait',
	LV: 'Latvia',
	LB: 'Lebanon',
	LY: 'Libya',
	LT: 'Lithuania',
	LU: 'Luxembourg',
	MY: 'Malaysia',
	MX: 'Mexico',
	MA: 'Morocco',
	NP: 'Nepal',
	NL: 'Netherlands',
	NZ: 'New Zealand',
	NI: 'Nicaragua',
	NG: 'Nigeria',
	NO: 'Norway',
	OM: 'Oman',
	PK: 'Pakistan',
	PA: 'Panama',
	PY: 'Paraguay',
	PE: 'Peru',
	PH: 'Philippines',
	PL: 'Poland',
	PT: 'Portugal',
	PR: 'Puerto Rico',
	QA: 'Qatar',
	RO: 'Romania',
	RU: 'Russia',
	SA: 'Saudi Arabia',
	SN: 'Senegal',
	RS: 'Serbia',
	SG: 'Singapore',
	SK: 'Slovakia',
	SI: 'Slovenia',
	ZA: 'South Africa',
	ES: 'Spain',
	LK: 'Sri Lanka',
	SE: 'Sweden',
	CH: 'Switzerland',
	SY: 'Syria',
	TW: 'Taiwan',
	TZ: 'Tanzania',
	TH: 'Thailand',
	TN: 'Tunisia',
	TR: 'Turkey',
	UG: 'Uganda',
	UA: 'Ukraine',
	AE: 'United Arab Emirates',
	GB: 'United Kingdom',
	US: 'United States',
	UY: 'Uruguay',
	VE: 'Venezuela',
	VN: 'Vietnam',
	YE: 'Yemen',
	ZM: 'Zambia',
	ZW: 'Zimbabwe',
};
